image: php:7.2

variables:
    TYPO3_VERSION: "8.7"

before_script:
    # Install git (needed by composer)
    - apt-get update -yqq && apt-get install git -yqq

    # Install zip (needed by composer)
    - apt-get update -yqq && apt-get install zlib1g-dev -yqq
    - docker-php-ext-install zip

    # Install composer
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

    # Install parallel needed for linting PHP and functional tests
    - apt-get update -yqq && apt-get install parallel -yqq

    # Install MySQL (needed for TYPO3)
    - docker-php-ext-install mysqli

stages:
    - test

Code Style:
    stage: test
    script:
        - composer install --prefer-dist --no-progress
        - vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --stop-on-violation --using-cache=no

Lint PHP:
    stage: test
    script:
        - find . -name \*.php ! -path "./.Build/*" ! -path "./vendor/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;;

.Functional Tests Template: &functional_tests
    stage: test
    services:
        - mysql
    variables:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: typo3
        typo3DatabaseName: typo3
        typo3DatabaseHost: mysql
        typo3DatabaseUsername: root
        typo3DatabasePassword: root
    script:
        - composer require typo3/minimal="$TYPO3_VERSION"
        - find '.Build/Web/typo3conf/ext/twig/Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; vendor/bin/phpunit -c vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml {}';

#Unit Tests:
#    stage: test
#    script:
#        - composer require typo3/minimal="$TYPO3_VERSION"
#        - vendor/bin/phpunit -c vendor/nimut/testing-framework/res/Configuration/UnitTests.xml .Build/Web/typo3conf/ext/twig/Tests/Unit/;

Functional Tests (8.7):
    <<: *functional_tests
    variables:
        TYPO3_VERSION: "8.7"

Functional Tests (9.2):
    <<: *functional_tests
    variables:
        TYPO3_VERSION: "9.2"
